services:
  gttool:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./workspaces:/app/workspaces
      - /mnt/cps_persistent1_shared/datasets/public:/mnt/datasets/public:ro
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    command: ["--help"]

  dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./workspaces:/app/workspaces
      - /mnt/cps_persistent1_shared/datasets/public:/mnt/datasets/public:ro
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: ["/bin/bash"]
